### ISSUE TITLE
how to save file in dirctory

### ISSUE THREAD

**Issue by kark445** [samsamsam-iptvplayer/hlsdl#1]
how to save output ts file in dirctory..

**Comment by samsamsam-iptvplayer** [comment]
hlsdl http://xxxx.yy/xxxx/xxx.m3u8 **-o** /dir1/dir2/file.ts

**Comment by kark445** [comment]
can v do this ..
hlsdl http://xxxx.yy/xxxx/xxx.m3u8 -o | ffmpeg -loglevel quiet -i - -vcodec copy -strict -2 -acodec copy -preset ultrafast -scodec copy -hls_time 10 -hls_list_size 6 /mnt/hls/241.m3u8

**Comment by samsamsam-iptvplayer** [comment]
You want to output data to the stdout.
At now this is not possible but such option could be added.

**Comment by kark445** [comment]
pls add if u can....tnx

**Comment by samsamsam-iptvplayer** [comment]
Added in version v0.22
https://github.com/samsamsam-iptvplayer/hlsdl/commit/13658c4fe53923141d3dabf0f097d605a76ee9bc

You can use as follows:
`hlsdl http://xxxx.yy/xxxx/xxx.m3u8  -o - | ffmpeg -loglevel quiet -i - -vcodec copy -strict -2 -acodec copy -preset ultrafast -scodec copy -hls_time 10 -hls_list_size 6 /mnt/hls/241.m3u8`

Regards,
SSS

**Comment by kark445** [comment]
working a1 now...tnx
